=== d-suvorov/EFSM-tools/qbf/Unbeast-0.6b/SynSpec.dtd
<!-- DTD format file for Specification for Unbounded Bounded Synthesis -->
<!-- (C) 2008 Ruediger Ehlers -->

<!-- General Description -->
<!ELEMENT SynthesisProblem (Title,Description,PathToLTLCompiler,GlobalInputs,GlobalOutputs,Assumptions?,Specification)>
<!ELEMENT Title (#PCDATA)>
<!ELEMENT Description (#PCDATA)>
<!ELEMENT GlobalInputs (Bit)*>
<!ELEMENT GlobalOutputs (Bit)*>
<!ELEMENT Bit (#PCDATA)>
<!ELEMENT PathToLTLCompiler (#PCDATA)>

<!-- Specification -->
<!ELEMENT False EMPTY>
<!ELEMENT True EMPTY>
<!ELEMENT Specification (LTL)*>
<!ELEMENT Assumptions (LTL)*>
<!ELEMENT LTL (Or|And|Not|X|Var|F|G|U|WU|Iff|False|True)>
<!ELEMENT Or (Or|And|Not|X|Var|F|G|U|WU|Iff|False|True)+>
<!ELEMENT And (Or|And|Not|X|Var|F|G|U|WU|Iff|False|True)+>
<!ELEMENT Not (Or|And|Not|X|Var|F|G|U|WU|Iff|False|True)>
<!ELEMENT Iff ((Or|And|Not|X|Var|F|G|U|WU|Iff|False|True),(Or|And|Not|X|Var|F|G|U|WU|Iff|False|True))>
<!ELEMENT X (Or|And|Not|X|Var|F|G|U|WU|Iff|False|True)>
<!ELEMENT G (Or|And|Not|X|Var|F|G|U|WU|Iff|False|True)>
<!ELEMENT F (Or|And|Not|X|Var|F|G|U|WU|Iff|False|True)>
<!ELEMENT U ((Or|And|Not|X|Var|F|G|U|WU|Iff|False|True),(Or|And|Not|X|Var|F|G|U|WU|Iff|False|True))>
<!ELEMENT WU ((Or|And|Not|X|Var|F|G|U|WU|Iff|False|True),(Or|And|Not|X|Var|F|G|U|WU|Iff|False|True))>

<!ELEMENT Var (#PCDATA)>

=== d-suvorov/EFSM-tools/evaluation/Unbeast-0.6b/Examples/Mutex2.xml
<?xml version="1.0" encoding="ISO-8859-1" ?>
<!DOCTYPE SynthesisProblem SYSTEM "SynSpec.dtd">
<SynthesisProblem>
  <Title>A variation of a mutex, unrealisable</Title>
  <Description>A not quite complex example</Description>
  <PathToLTLCompiler>ltl2ba-1.1/ltl2ba -f</PathToLTLCompiler>
  <GlobalInputs>
    <Bit>Request0</Bit>
    <Bit>Request1</Bit>
  </GlobalInputs>
  <GlobalOutputs>
    <Bit>Grant0</Bit>
    <Bit>Grant1</Bit>
  </GlobalOutputs>
  <Assumptions>
    <LTL><G><F><Not><Var>Request0</Var></Not></F></G></LTL>
    <LTL><G><F><Not><Var>Request1</Var></Not></F></G></LTL>
  </Assumptions>
  <Specification>
    <LTL><G><And><Not><Var>Grant0</Var></Not>
       <Not><Var>Grant1</Var></Not></And></G></LTL>
    <LTL><G><Or><Not><Var>Request0</Var></Not><F>
       <Var>Grant0</Var></F></Or></G></LTL>
    <LTL><G><Or><Not><Var>Request1</Var></Not><F>
       <Var>Grant1</Var></F></Or></G></LTL>
  </Specification>
</SynthesisProblem>

=== d-suvorov/EFSM-tools/evaluation/Unbeast-0.6b/Examples/BasicLivenessTest.xml
<?xml version="1.0" encoding="ISO-8859-1" ?>
<!DOCTYPE SynthesisProblem SYSTEM "SynSpec.dtd">
<SynthesisProblem>
  <Title>Just a test</Title>
  <Description>A test with liveness components</Description>
  <PathToLTLCompiler>ltl2ba-1.1/ltl2ba -f</PathToLTLCompiler>
  <GlobalInputs>
    <Bit>x</Bit>
  </GlobalInputs>
  <GlobalOutputs>
    <Bit>y</Bit>
  </GlobalOutputs>
  <Assumptions>
    <LTL><G><Not><Var>x</Var></Not></G></LTL>
    <LTL><G><F>
      <Or>
        <And><Not><Var>x</Var></Not><Not><Var>y</Var></Not></And>
        <And><Var>x</Var><Var>y</Var></And>
      </Or>
    </F></G></LTL>
  </Assumptions>
  <Specification>
    <LTL><G>
      <Or>
        <And><Not><Var>x</Var></Not><Not><Var>y</Var></Not></And>
        <And><Var>x</Var><Var>y</Var></And>
      </Or>
    </G></LTL>
    <LTL><G><F><Var>y</Var></F></G></LTL>
  </Specification>
</SynthesisProblem>

=== d-suvorov/EFSM-tools/evaluation/Unbeast-0.6b/bkp.xml
<?xml version="1.0" encoding="ISO-8859-1" ?>
<!DOCTYPE SynthesisProblem SYSTEM "SynSpec.dtd">
<SynthesisProblem>
  <Title>A mutex</Title>
  <Description>A not quite complex example</Description>
  <PathToLTLCompiler>ltl2ba-1.1/ltl2ba -f</PathToLTLCompiler>
  <GlobalInputs>
    <Bit>e11</Bit>
    <Bit>e12</Bit>
    <Bit>e2</Bit>
    <Bit>e3</Bit>
    <Bit>e4</Bit>
  </GlobalInputs>
  <GlobalOutputs>
    <Bit>z1</Bit>
    <Bit>z2</Bit>
    <Bit>z3</Bit>
    <Bit>z239</Bit>
  </GlobalOutputs>
  <Assumptions>
  </Assumptions>
  <Specification>
    <LTL>
	<G>
	    <Or> 
		<Not>
		    <And>
			<Var>e11</Var>
			<Not><Var>e12</Var></Not>
			<Not><Var>e2</Var></Not>
			<Not><Var>e3</Var></Not>
			<Not><Var>e4</Var></Not>
		    </And>
		</Not>
		<Or>
		    <And>
			<Var>z1</Var>
			<Not><Var>z2</Var></Not>
			<Not><Var>z3</Var></Not>
			<Not><Var>z239</Var></Not>
		    </And>
		    <And>
			<Var>z239</Var>
			<Not><Var>z1</Var></Not>
			<Not><Var>z2</Var></Not>
			<Not><Var>z3</Var></Not>
		    </And>
		</Or>
	    </Or>
	</G>
    </LTL>
 </Specification>
</SynthesisProblem>
